name: 'f1_dbt'
version: '1.0.0'
config-version: 2

profile: 'f1_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1_dbt:
    optimized:
      +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table